### PR TITLE
Allow custom headers in the response

### PR DESCRIPTION
**Pull request by earnaway**

### CODE REVIEW

**Comment by maximebeaudoin** [comment]
You commit message doesn't represent the purpose of your commit. You can use `git commit --amend -m "Added optional headers arguments to most methods. Added default value for headers in interface"`.

Unfortunately, you have to force push after this change and because you working in master, this PR will be closed.

**Comment by earnaway** [comment]
Thanks for the heads up @maximebeaudoin. Would you be able to tag that commit so I can refer it to in my composer packages for use in our codebase, to not have to use our forked version.

**Comment by maximebeaudoin** [comment]
I'll do that today for sure. I have to do some tests before just in case.

**Comment by earnaway** [comment]
Perfect, thanks again!

**Comment by maximebeaudoin** [comment]
New tag 0.12.0 now available.

**Comment by earnaway** [comment]
Excellent, thanks very much!

**Pull request merged**
